export const inscriptionFields = [
  {
    type: 'dropdown',
    label: 'Rol',
    id: 'rolField',
    name: 'rol',
    icon: '/images/svg/Chevron.svg',
    tabindex: 1,
  },
  {
    type: 'dropdown',
    label: 'Disponibilidad Horaria',
    id: 'timeAvailabilityField',
    name: 'timeAvailability',
    icon: '/images/svg/Chevron.svg',
    tabindex: 2,
  },
  {
    type: 'dropdown',
    label: 'Language',
    id: 'languageField',
    name: 'language',
    icon: '/images/svg/Chevron.svg',
    tabindex: 3,
  },
  {
    type: 'dropdown',
    label: 'Frameworks',
    id: 'frameworksFields',
    name: 'frameworks',
    icon: '/images/svg/Chevron.svg',
    tabindex: 4,
  },
  {
    type: 'ask',
    label: '¿Te gustaría ser Team Leader?',
    id: 'askTeamLeaderField',
    name: 'isTeamLeader',
    tabindex: 5,
    items: [
      { id: 'askYes', placeholder: 'Si', value: 'true' },
      { id: 'askNo', placeholder: 'No', value: 'false' },
    ],
  },
];
