export const inscriptionFields = [
  {
    type: 'dropdown',
    label: 'Tipo de simulación',
    id: 'simulationTypeField',
    name: 'type',
    icon: '/images/svg/Chevron.svg',
    tabindex: 1,
    defaultValue: '1',
    items: [
      { placeholder: 'Web App', value: '1' },
      { placeholder: 'No code App', value: '2' },
      { placeholder: 'Mobile App', value: '3' },
    ],
  },
  {
    type: 'dropdown',
    label: 'Rol',
    id: 'rolField',
    name: 'rol',
    icon: '/images/svg/Chevron.svg',
    tabindex: 2,
    defaultValue: '1',
    items: [
      { placeholder: 'UX/UI', value: '1' },
      { placeholder: 'Desarrollador Web', value: '2' },
      { placeholder: 'Desarrollador Mobile', value: '3' },
      { placeholder: 'Project Manager', value: '4' },
      { placeholder: 'QA', value: '5' },
    ],
  },
  {
    type: 'dropdown',
    label: 'Disponibilidad Horaria',
    id: 'timeAvailabilityField',
    name: 'timeAvailability',
    icon: '/images/svg/Chevron.svg',
    tabindex: 3,
    defaultValue: '1',
    items: [
      { placeholder: 'Turno Tarde', value: '1' },
      { placeholder: 'Turno Mañana', value: '2' },
      { placeholder: 'Full time', value: '3' },
    ],
  },
  {
    type: 'stack',
    label: 'Stack',
    id: 'stackField',
    name: 'stack',
    icon: '/images/svg/PlusCircle.svg',
    tabindex: 4,
  },
  {
    type: 'ask',
    label: '¿Te gustaría ser Team Leader?',
    id: 'askTeamLeaderField',
    name: 'isTeamLeader',
    tabindex: 5,
    items: [
      { id: 'askYes', placeholder: 'Si', value: 'true' },
      { id: 'askNo', placeholder: 'No', value: 'false' },
    ],
  },
];
