export const manageTeamsFields = [
  {
    id: 'eventNumberField',
    name: 'eventNum',
    type: 'text',
    label: 'Id de Evento para asignar equipos',
    tabindex: 1,
  },
  {
    id: 'scheduleNameField',
    name: 'scheduleNom',
    type: 'text',
    label: 'Horario Especifico del Evento para asignar equipos',
    tabindex: 2,
  },
  {
    id: 'frameworkFrontField',
    name: 'frameworkFront',
    type: 'text',
    label: 'Nombre del Framework del rol Frontend',
    tabindex: 3,
  },
  {
    id: 'frontQuantitybField',
    name: 'frontQuantity',
    type: 'number',
    label: 'Numero de participantes bajo rol Frontend por equipo',
    tabindex: 4,
  },
  {
    id: 'backQuantitybField',
    name: 'backQuantity',
    type: 'number',
    label: 'Numero de participantes bajo rol Backend por equipo',
    tabindex: 5,
  },
  {
    id: 'qaQuantitybField',
    name: 'qaQuantity',
    type: 'number',
    label: 'Numero de participantes bajo rol QA Tester por equipo',
    tabindex: 6,
  },
  {
    id: 'pmQuantitybField',
    name: 'pmQuantity',
    type: 'number',
    label: 'Numero de participantes bajo rol Project Manager por equipo',
    tabindex: 7,
  },
  {
    id: 'uxQuantitybField',
    name: 'uxQuantity',
    type: 'number',
    label: 'Numero de participantes bajo rol Diseñador UX/UI por equipo',
    tabindex: 8,
  },
];
