@authToken={{$dotenv API_TOKEN}}
@baseUrl={{$dotenv URL}}

### Verifica si el token del usuario es valido
GET {{baseUrl}}/api/auth/check-login
content-type: application/json
Cookie: token={{authToken}}