GET https://nocountry.up.railway.app/api/teams/byUser
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpc2FiZWxtYXJ0aW5lejE5LjMwQGdtYWlsLmNvbSIsInVzZXJJZCI6ImUyMGI4Mzk5LTc1MTAtNDgwMC1iYjYzLTQzM2Y1NmFlNTM4MyIsImV4cCI6MTczMDI1MDgxMCwiaWF0IjoxNzMwMjQ3MjEwfQ.QmjEc0PNuaUtavAJM0xNy26D53Be9RZno3LhgMJYAMU