@authToken={{$dotenv API_TOKEN}}
@baseUrl={{$dotenv URL}}

### Recupera los datos necesatios para inscribirte a un evento (Seleccionado, cohorte, etc)
# @prompt projectTypeId ID del tipo del proyecto(Puedes obtenerlo en projecttype.api.rest) 
GET {{baseUrl}}/api/event-records/register-form/{{projectTypeId}}
content-type: application/json
Cookie: token={{authToken}}