@authToken={{$dotenv API_TOKEN}}
@baseUrl={{$dotenv URL}}

### Recupera el equipo de un evento del usuario
GET {{baseUrl}}/api/participants/find_all_by_team_id
content-type: application/json
Cookie: token={{authToken}}

{
    "teamId": "123"
}