GET https://nocountry.up.railway.app/api/project-types
content-type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJjb3NAZ21haWwuY29tIiwidXNlcklkIjoiZmMzN2NhOWItZTc2Ny00ZjUzLThiN2YtNjY2ZTAzZTNmNGMwIiwiZXhwIjoxNzMwMDg4MDY3LCJpYXQiOjE3MzAwODQ0Njd9.vTbr_TeLFFg1-9VWhkQ2SMcI80WYmw6apBX9dk1iU8c