@authToken={{$dotenv API_TOKEN}}
@baseUrl={{$dotenv URL}}

### Recupera todos los equipos (? no me queda claro el uso de esto)
GET {{baseUrl}}/api/teams/page
content-type: application/json
Cookie: token={{authToken}}