import { cn } from '@/lib/utils';
import { openSans } from '@/styles/font';
import '../styles/globals.css';

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Los archivos "layout" son componentes que se renderizan en todas las paginas (hacia abajo de las rutas)
// Se ejecutan antes de la pagina
// Se pueden usar para agregar un mismo layout y no repetir, cambiar la meta data de la pagina entre otros
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // La funcion cn es una utilidad para combinar(mergear) clases de css
        className={cn(openSans.className, openSans.variable)}>
        {children}
      </body>
    </html>
  );
}
