name: Deploy

on:
  workflow_run:
    workflows: [ciFE]
    types:
      - completed
    branches:
      - develop

concurrency:
  group: gd-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup/ Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.7.0
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.7.0

      - name: Setup/ Install pnpm 9.7.0 manually
        run: npm install -g pnpm@9.7.0

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        working-directory: ./client
        run: railway up --service=S18-04-ft-Java-React -d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
